### ISSUE TITLE
Instantiating new objects with arguments

### ISSUE THREAD

**Issue by IDme** [janlelis/has_many_booleans#1]
Seems that doing Model.new(:boolean_argument_active => true) does not work, as the boolean fields are not yet created, so the model will not respond to respective attributes, so assigning will fail.

Also defining the boolean accessors before calling super in initialize won't work as the method defining logic depends on AR::Base stuff already being wired and responding to db attributes.

One solution would be to call super without any arguments, then initialize the boolean column methods, and then assign self.attributes = *args (initialize calls the same setter internally anyhow, so everything should be solid)

Another issue is that the extension will not treat form values the same way ActiveRecord does. Meaning "0" and "false" are treated as true, whereas for consistency they should be treated as normally. This can be achieved via comparing the new value (given to the setter) with ActiveRecord::ConnectionAdapters::ColumnDefinition::TRUE_VALUES or FALSE_VALUES to easily parse the boolean value. I guess this could be done via mapping the FALSE_VALUES to has_many_booleans :false_values options, but this still would mean that "foobar" would pass as true (unless its additionally mapped).

**Comment by janlelis** [comment]
Hi troopswap, many thanks for your feedback.

I'll try to fix the issues within the next days.

**Comment by janlelis** [comment]
Hi troopswap,
the second issue is solved with this push. The default for :false_values is now the ar's one and there is a new :true_values array and :unknown_value option. The :unknown_value will be the new value for a boolean, if it is not in :false_values or :true_values. Default for unknown is true, you can change it to false for ar behaviour.

However, I haven't solved the first issue so far... Your suggestions are good and would lead to something like this:
    def initialize(attributes = nil) # :nodoc:
      super()
      initialize_booleans
      self.attributes = attributes unless attributes.nil?
      yield self if block_given?
    end

The only problem is, that the after_initialize callback wouldn't have access to the new attrs. It's probably time for some meta programming voodoo xD,

**Comment by janlelis** [comment]
Ok, should now work, thank you again :)

inialize code:
    def initialize(attributes = nil) # :nodoc:

```
  if init_callback_defined = respond_to?(:after_initialize)
    instance_eval do
      alias tmp_after_initialize after_initialize
      undef after_initialize
    end
  end

  super()
  initialize_booleans
  self.attributes = attributes unless attributes.nil?
  result = yield self if block_given?

  if init_callback_defined
    instance_eval do
      alias after_initialize tmp_after_initialize
      undef tmp_after_initialize
      if RAILS2
        callback(:after_initialize)
      else
        _run_initialize_callbacks
      end
    end
  end

  result
end
```

**Comment by perfectline** [comment]
This looks really nice, thanks for the prompt response also.
P.S it was me who posted under "troopswap" account before on accident :)
